[package]
name = "pathtest1"
version = "0.1.0"
authors = ["Kenton Hamaluik <kenton@hamaluik.ca>"]
edition = "2018"

[dependencies]
pathfinding = "~1.0"
serde = "~1.0"
serde_json = "~1.0"
serde_derive = "~1.0"
